jw_assistant/jw_assistant/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'), #Dont forget the index
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/',include('profiles.urls', namespace='profiles')),
    url(r'^profiles/', include("django.contrib.auth.urls")),
    url(r'^congregations/',include('congregations.urls', namespace='congregations')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jw_assistant/profiles/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'profiles'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="profiles/login.html"), name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.sign_up_view, name="signup"),
    url(r'^(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='detail'),
    url(r'^update/(?P<pk>\d+)/$', views.UserProfileUpdateView.as_view(), name='update'),
    #url(r'^delete/(?P<pk>\d+)/$', views.ProfileDeleteView.as_view(), name='delete'),
    url(r'^confirm_delete/(?P<pk>\d+)/$', views.profile_confirm_delete_view, name="confirm_delete"),
    url(r'^delete/(?P<pk>\d+)/$', views.profile_delete_view, name="delete"),
]

jw_assistant/profiles/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse # For update and create views
from congregations.models import Congregation
from django.db.models.signals import post_save  #is emitted by django whenever a model instance gets saved to the database
from django.dispatch import receiver #Decorator

import os.path

#@receiver(post_save, sender=User)
#def ensure_profile_exists(sender, **kwargs):
    #if kwargs.get('created', False):
        #UserProfile.objects.get_or_create(user=kwargs.get('instance'))

# PROFILES MODELS
# Create your models here.
class UserProfile(models.Model):

    # Create relationship to extend the build in User Model (don't inherit from User!)
    user = models.OneToOneField(User, related_name='profile')
    # username, first_name, last_name, email, already defined in build in User Model
    # Add any additional attributes you want
    phone = models.CharField(max_length=40, null=True, blank=True) # add country prefix later
    congregation = models.ForeignKey(Congregation, on_delete=models.SET_NULL, null=True, blank=True, related_name='user_profiles')
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)
    street = models.CharField(max_length=150, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    zip_code = models.CharField(max_length=30, null=True, blank=True)
    state = models.CharField(max_length=70, null=True, blank=True)
    country = models.CharField(max_length=70, null=True, blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

    def get_absolute_url(self):
        return reverse('profiles:detail', kwargs={'pk':self.pk}) # For update and create views

    def get_picture(self):
        default_picture = settings.MEDIA_URL + 'profile_pics/default-picture.png'
        try:
            filename = settings.MEDIA_ROOT + '/profile_pics/' + self.user.username + '.jpg'
            picture_url = settings.MEDIA_URL + 'profile_pics/' + self.user.username + '.jpg'
            if os.path.isfile(filename):
                return picture_url
            else:
                return default_picture
        except Exception:
            return default_picture

    def get_screen_name(self):
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:
            return self.user.username

jw_assistant/profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from profiles.models import UserProfile
from congregations.models import Congregation
from django.contrib.auth.password_validation import MinimumLengthValidator, UserAttributeSimilarityValidator, CommonPasswordValidator, NumericPasswordValidator
from django.core.exceptions import ValidationError
from django.conf import settings

def DomainValidator(value):
    if '*' not in settings.ALLOWED_SIGNUP_DOMAINS:
        try:
            domain = value[value.index("@"):]
            if domain not in settings.ALLOWED_SIGNUP_DOMAINS:
                raise ValidationError('Invalid domain. Allowed domains on this network: {0}'.format(','.join(settings.ALLOWED_SIGNUP_DOMAINS)))  # noqa: E501

        except Exception:
            raise ValidationError('Invalid domain. Allowed domains on this network: {0}'.format(','.join(settings.ALLOWED_SIGNUP_DOMAINS)))  # noqa: E501

def ReservedWordsValidator(value):
    reserved_words = ['admin', 'settings', 'news', 'about', 'help',
                           'signin', 'signup', 'signout', 'terms', 'privacy',
                           'cookie', 'new', 'login', 'logout', 'administrator',
                           'join', 'account', 'username', 'root', 'blog',
                           'user', 'users', 'billing', 'subscribe', 'reviews',
                           'review', 'blog', 'blogs', 'edit', 'mail', 'email',
                           'home', 'job', 'jobs', 'contribute', 'newsletter',
                           'shop', 'profile', 'register', 'auth',
                           'authentication', 'campaign', 'config', 'delete',
                           'remove', 'forum', 'forums', 'download',
                           'downloads', 'contact', 'blogs', 'feed', 'feeds',
                           'faq', 'intranet', 'log', 'registration', 'search',
                           'explore', 'rss', 'support', 'status', 'static',
                           'media', 'setting', 'css', 'js', 'follow',
                           'activity', 'questions', 'articles', 'network', ]

    if value.lower() in reserved_words:
        raise ValidationError('This is a reserved word.')


def UsernameValidator(value):
    if '@' in value or '+' in value or '-' in value:
        raise ValidationError('Enter a valid username. Please avoid using "@" "+" "-" in your username.')


def UniqueEmailValidator(value):
    if User.objects.filter(email__iexact=value).exists():
        raise ValidationError('User with this Email already exists.')

def UniqueUsernameIgnoreCaseValidator(value):
    if User.objects.filter(username__iexact=value).exists():
        raise ValidationError('User with this Username already exists.')

class UserForm(forms.ModelForm):
    username = forms.CharField(label='', help_text=' ', widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), error_messages={'error_name':'error_messages'})
    confirm_password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}), error_messages={'error_name':'error_messages'})
    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={'placeholder':'Email address'}))
    first_name = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'First name'}))
    last_name = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Last name'}))

    class Meta():
        model = User
        fields = ('username', 'password', 'confirm_password', 'email', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].validators.append(ReservedWordsValidator)
        self.fields['username'].validators.append(UsernameValidator)
        self.fields['username'].validators.append(UniqueUsernameIgnoreCaseValidator)
        self.fields['email'].validators.append(UniqueEmailValidator)
        self.fields['email'].validators.append(DomainValidator)

    def clean(self):
        cleaned_data = super(UserForm, self).clean()

        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password:
            if password != confirm_password:
                raise ValidationError("The two password fields must match.")
                widgets = {
                    'password': PasswordInput(attrs={'style': 'border-color:red;'}),
                    'confirm_password': PasswordInput(attrs={'class': 'error'}),
                }
        return cleaned_data

class UserProfileForm(forms.ModelForm):
    phone = forms.CharField(label='', widget=forms.NumberInput(attrs={'placeholder':'Phone'}), required=False)
    congregation = forms.ModelChoiceField(label='', queryset=Congregation.objects.all(), empty_label="Select your congregation or add it later.", required=False)
    street = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Street'}), required=False)
    city = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'City'}), required=False)
    zip_code = forms.CharField(label='', widget=forms.NumberInput(attrs={'placeholder':'Zip code or Postal code'}), required=False)
    state = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'State'}), required=False)
    country = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Country'}), required=False)

    class Meta():
        model = UserProfile
        fields = ('profile_pic', 'congregation', 'phone', 'street', 'city', 'zip_code', 'state', 'country')

class LoginForm(forms.Form):
    username = forms.CharField(label='', help_text=' ', widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), error_messages={'error_name':'error_messages'})

jw_assistant/profiles/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, get_object_or_404
from . import forms
from . import models
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView, FormView)

from django.core.urlresolvers import reverse_lazy

from django.contrib.auth.models import User

# extra for profiles deletion
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse

from django.core.exceptions import ObjectDoesNotExist

def sign_up_view(request):

    registered = False

    user_form_errors = []
    profile_form_errors = []

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = forms.UserForm(data=request.POST) #To get validated data --> form.cleaned_data['subject']..
        profile_form = forms.UserProfileForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)
            for error in user_form.errors:
                user_form_errors.append(error)
            for error in profile_form_errors:
                profile_form_errors.append(error)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = forms.UserForm()
        profile_form = forms.UserProfileForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'profiles/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered,
                           'user_form_errors':user_form_errors,
                           'profile_form_errors':profile_form_errors})

class ProfileDetailView(DetailView):
    #context_object_name = 'profile_details'
    model = User
    template_name = 'profiles/profile_details.html'

    def get_context_data(self,**kwargs):
        context  = super().get_context_data(**kwargs)
        try:
            profile_details = models.UserProfile.objects.get(user=self.request.user)
            context['profile_details'] = profile_details
        except ObjectDoesNotExist:
            profile_details = User.objects.get(pk=self.request.user.pk)
            context['profile_details'] = profile_details
        return context

class UserProfileUpdateView(UpdateView):
    #fields = '__all__'
    template_name = 'profiles/profile_form.html'
    form_class = forms.UserForm
    model = User

class ProfileDeleteView(DeleteView):
    model = models.UserProfile
    success_url = reverse_lazy("profiles:logout")

def profile_confirm_delete_view(request, pk):
    return render(request, 'profiles/userprofile_confirm_delete.html',
                  {'pk':pk})

def profile_delete_view(request, pk):
    profile_to_delete = get_object_or_404(User, pk=pk)
    profile_to_delete.delete()
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

jw_assistant/profiles/templates/profiles/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block block_title %} Sign Up {% endblock %}

{% block body_block %}

  <!-- Contact Section -->
  <section id="contact">
      <div class="container">

          <div class="row">
              <div class="col-lg-12 text-center">
                  <h3 class="form-signin-heading" style="margin-top:15px;">Login Here</h3>
                  <hr class="star-primary">
              </div>
          </div>

          <div class="row">
              <div class="col-lg-8 col-lg-offset-2">

                <form class="form-signin" method="POST">


                  {% for error in errors %}
                    <div class = "alert alert-danger alert-dismissable">
                      <p> {{ error }} </p>
                    </div>
                  {% endfor %}

                  {% csrf_token %}

                  {% if form.non_field_errors %}
                    <div class = "alert alert-danger alert-dismissable">
                      <p> {{ form.non_field_errors }} </p>
                    </div>
                  {% endif %}

                  <div class="form-group">
                      <label class="control-label  " for="id_username"></label>
                      <div class=" ">
                          <input type="text" name="username" autofocus="" maxlength="254" class=" form-control" required="" id="id_username" placeholder="Username">
                      </div>
                  </div>

                  <div class="form-group">
                      <label class="control-label  " for="id_password"></label>
                      <div class=" ">
                          <input type="password" name="password" class=" form-control" required="" id="id_password" placeholder="Password">
                      </div>
                  </div>

                  <input type="submit" name="" value="Login" class="btn btn-lg btn-success btn-block">
                  <p><a href="#" class="btn btn-lg btn-warning btn-block">Forgot Password</a></p>
                  <p><a href="{% url 'profiles:signup' %}" class="btn btn-lg btn-info btn-block">Register</a></p>

                </form>

              </div>
          </div>

      </div>

  </section>



{% endblock %}

jw_assistant/profiles/templates/profiles/profile_details.html
{% extends "base.html" %}
{% load bootstrap %}
{% load staticfiles %}

{% block body_block %}

<!-- form Section -->
    <section style="background-color:#f5f5f5;">
        <div class="container">
            <div class="row" id="profileDetails">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="text-center">
                      <h3>{{user.username}} Details</h3>
                      <hr class="star-primary">
                  </div>

                  {% if profile_details.profile_pic %}
                    <div class="profil_pic">
                        <img src="/media/{{profile_details.profile_pic}}"
                        class="img-responsive img-square" alt="{{user.username}}'s profile picture">
                    </div>
                  {% else %}
                    <div class="profil_pic">
                        <img src="/media/profile_pics/default-picture.png"
                        class="img-responsive img-square" alt="{{user.username}}'s profile picture">
                    </div>
                  {% endif %}
                    <p><strong>Username:</strong> {{user.username}}</p>
                    <p><strong>Email:</strong> {{user.email}}</p>
                    <p><strong>Phone:</strong> {{profile_details.phone}}</p>
                    <p><strong>Congregation:</strong> {{profile_details.congregation}}</p>
                    <p><strong>Street Address:</strong> {{profile_details.street}}</p>
                    <p><strong>City:</strong> {{profile_details.city}}</p>
                    <p><strong>Zip Code:</strong> {{profile_details.zip_code}}</p>
                    <p><strong>State:</strong> {{profile_details.state}}</p>
                    <p><strong>Country:</strong> {{profile_details.country}}</p>
                    <div id="congregation-btns">
                        <a class="col-lg-6 col-md-6 col-sm-6 col-xs-12 btn-lg btn-warning"
                        href="{% url 'profiles:update' pk=user.pk %}">Update</a>
                        <a class="col-lg-6 col-md-6 col-sm-6 col-xs-12 btn-lg btn-danger"
                        href="{% url 'profiles:confirm_delete' pk=user.pk %}">Delete</a>
                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

jw_assistant/profiles/templates/profiles/profile_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block block_title %} Sign Up {% endblock %}

{% block body_block %}

  <!-- Contact Section -->
  <section id="contact">
      <div class="container">
          <div class="row">
              <div class="col-lg-12 text-center">
                  <h3 class="form-signin-heading" style="margin-top:15px;">Update Profile</h3>
                  <hr class="star-primary">
              </div>
          </div>
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2">
                  <form enctype="multipart/form-data" method="POST" class="form-signin">

                      {% csrf_token %}
                      {% if errors %}
                        <div class = "alert alert-danger alert-dismissable">
                            {% for error in errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                      {% endif %}
                    
                      {{ form | bootstrap }}
                      <input type="submit" name="" value="Update" class="btn btn-lg btn-success btn-block" style="margin-bottom:40px;">

                  </form>
              </div>
          </div>
      </div>

  </section>

{% endblock %}

jw_assistant/profiles/templates/profiles/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block block_title %} Sign Up {% endblock %}

{% block body_block %}

  <!-- Contact Section -->
  <section id="contact">
      <div class="container">
          <div class="row">
              <div class="col-lg-12 text-center">

      {% if registered %}

                  <h3 class="form-signin-heading alert alert-success" style="margin-top:15px;">Thank you for registering!</h3>
                  <h3 class="form-signin-heading"><a href="#">Click here to go to your profile</a></h3>

      {% else %}

                  <h3 class="form-signin-heading" style="margin-top:15px;">Register Here</h3>
                  <hr class="star-primary">
              </div>
          </div>
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2">
                  <form enctype="multipart/form-data" method="POST" class="form-signin">

                      {% csrf_token %}
                      {% if errors %}
                        <div class = "alert alert-danger alert-dismissable">
                            {% for error in errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                      {% endif %}
                      {{ user_form | bootstrap }}
                      <h5 style="text-align:center;margin-top:50px;"> Optional fields </h5>
                      {{ profile_form | bootstrap }}
                      <input type="submit" name="" value="Register" class="btn btn-lg btn-success btn-block" style="margin-bottom:40px;">

                  </form>
              </div>
          </div>
      </div>

      {% endif %}

  </section>

{% endblock %}

jw_assistant/profiles/templates/profiles/userprofile_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap %}
{% load staticfiles %}

{% block body_block %}

<!-- form Section -->
    <section style="background-color:#f5f5f5;height:490px;">
        <div class="container">
            <div class="row" id="delConfirmation" >
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="text-center">
                      <h3>Deletion Confirmation</h3>
                      <hr class="star-primary">
                  </div>
                  <p>Are you sure you want to delete <strong>your profile</strong>?</p>
                  <form method="post" class="row">
                      {% csrf_token %}
                      <a href="{% url 'profiles:delete' pk=user.pk%}"
                      class="col-lg-6 col-md-6 col-sm-6 col-xs-6 btn-lg btn-danger"
                      style="height:50px;border-radius:0;text-align:center;">
                          Delete
                      </a>
                      <a href="{% url 'profiles:detail' pk=user.pk%}"
                      class="col-lg-6 col-md-6 col-sm-6 col-xs-6 btn-lg btn-success"
                      style="height:50px;border-radius:0;text-align:center;">
                          Cancel
                      </a>
                  </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}